### ISSUE TITLE
Is there any documentation to setup it correctly for version greater then 60.  

### ISSUE THREAD

**Issue by sarifconrati** [wix/react-native-notifications#396]

**Comment by pipoblak** [comment]
Same problem here, i tried everything, and nothing works...

    "react": "16.9.0",
    "react-native": "0.61.2",

**Comment by jsina** [comment]
I'm also have some issue just like @pipoblak

**Comment by jsina** [comment]
@pipoblak @sarifconrati 
here is my workaround on these version of packages:
```
"react-native-notifications": "^2.0.6",
"react": "16.9.0",
"react-native": "0.61.2",
```
I follow this link for adding Manual linking:
**hint:**  for ``` Header Search Paths``` setting I've add ```"${PODS_CONFIGURATION_BUILD_DIR}/react-native-notifications"``` separately on _Debug_ and _Release_ `(don't forget the double quotation arount the path)`
also before running go to ```ios``` folder and run ```pod install``` again

**Comment by vanlinh** [comment]
I am using version 2.0.6 with react-native 0.61.2. It works fine on android, but got error during manually link on iOS. Could not build the app on xcode.
Any suggestion for this issue would be really appreciated!

**Comment by NickMendes** [comment]
Also cant get this to work on ```"react-native": "0.61.2"```

**Comment by msantang78** [comment]
I was able to make it work with the version 2.1.5 and RN 0.61.2

**Android**
add to the react-native.config.js to ignore it on the auto-linking:
```javascript
module.exports = {
  dependencies: {
    'react-native-notifications': {
      platforms: {
        android: null
      },
    },
 },
}
```

add to the settings.gradle:
```
include ':reactnativenotifications'
project(':reactnativenotifications').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-notifications/android/app')
```
build.gradle:
```
buildscript {
    ...
    dependencies {
        ...
        classpath 'com.google.gms:google-services:4.3.0' // <-- add this
    }
}
```


app/build.gradle:
```
android {
  defaultConfig {
     ...
     //add this
     missingDimensionStrategy "RNNotifications.reactNativeVersion", "reactNative60"
   }
}
dependencies {
    ...
    // add both
    implementation project(':reactnativenotifications');
    implementation 'com.google.firebase:firebase-core:16.0.7';
}
apply plugin: 'com.google.gms.google-services' // add this at the end of the file
```
MainApplication.java:
```java
 private final ReactNativeHost mReactNativeHost =
   
      @Override
      protected List<ReactPackage> getPackages() {
        @SuppressWarnings("UnnecessaryLocalVariable")
        List<ReactPackage> packages = new PackageList(this).getPackages();

        //add the package here (note the this.getApplication())
        packages.add(new RNNotificationsPackage(this.getApplication())); 
        return packages;
      }
```

**Ios**
```
cd ios
pod install
```
And follow the steps here :https://github.com/wix/react-native-notifications/blob/2.1.5/docs/installation.md
to edit the AppDelegate.m

**Comment by arnaudambro** [comment]
hi @msantang78 i did what you said for Android and here is what I have
```
error: cannot find symbol
          packages.add(new RNNotificationsPackage(this.getApplication()));
```

How can I import the package ?

**Comment by Bilal-Abdeen** [comment]
> I was able to make it work with the version 2.1.5 and RN 0.61.2
> 
> **Android**
> add to the react-native.config.js to ignore it on the auto-linking:
> 
> ```js
> module.exports = {
>   dependencies: {
>     'react-native-notifications': {
>       platforms: {
>         android: null
>       },
>     },
>  },
> }
> ```
> 
> add to the settings.gradle:
> 
> ```
> include ':reactnativenotifications'
> project(':reactnativenotifications').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-notifications/android/app')
> ```
> 
> build.gradle:
> 
> ```
> buildscript {
>     ...
>     dependencies {
>         ...
>         classpath 'com.google.gms:google-services:4.3.0' // <-- add this
>     }
> }
> ```
> 
> app/build.gradle:
> 
> ```
> android {
>   defaultConfig {
>      ...
>      //add this
>      missingDimensionStrategy "RNNotifications.reactNativeVersion", "reactNative60"
>    }
> }
> dependencies {
>     ...
>     // add both
>     implementation project(':reactnativenotifications');
>     implementation 'com.google.firebase:firebase-core:16.0.7';
> }
> apply plugin: 'com.google.gms.google-services' // add this at the end of the file
> ```
> 
> MainApplication.java:
> 
> ```java
>  private final ReactNativeHost mReactNativeHost =
>    
>       @Override
>       protected List<ReactPackage> getPackages() {
>         @SuppressWarnings("UnnecessaryLocalVariable")
>         List<ReactPackage> packages = new PackageList(this).getPackages();
> 
>         //add the package here (note the this.getApplication())
>         packages.add(new RNNotificationsPackage(this.getApplication())); 
>         return packages;
>       }
> ```
> 
> **Ios**
> 
> ```
> cd ios
> pod install
> ```
> 
> And follow the steps here :https://github.com/wix/react-native-notifications/blob/2.1.5/docs/installation.md
> to edit the AppDelegate.m

Thank you for this. It is very useful. In addition, to what you said, 
1. in (MainApplication.java) I have: 
```import com.wix.reactnativenotifications.RNNotificationsPackage;```
2. in (build.gradle), I applied the following change. I hope this will NOT break anything. This is my 1st RN project! This was necessary to avoid the error reported in #372 
```
- minSdkVersion = 16
+ minSdkVersion = 19
```

**Comment by m-inan** [comment]
> I was able to make it work with the version 2.1.5 and RN 0.61.2
> 
> **Android**
> add to the react-native.config.js to ignore it on the auto-linking:
> 
> ```js
> module.exports = {
>   dependencies: {
>     'react-native-notifications': {
>       platforms: {
>         android: null
>       },
>     },
>  },
> }
> ```
> 
> add to the settings.gradle:
> 
> ```
> include ':reactnativenotifications'
> project(':reactnativenotifications').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-notifications/android/app')
> ```
> 
> build.gradle:
> 
> ```
> buildscript {
>     ...
>     dependencies {
>         ...
>         classpath 'com.google.gms:google-services:4.3.0' // <-- add this
>     }
> }
> ```
> 
> app/build.gradle:
> 
> ```
> android {
>   defaultConfig {
>      ...
>      //add this
>      missingDimensionStrategy "RNNotifications.reactNativeVersion", "reactNative60"
>    }
> }
> dependencies {
>     ...
>     // add both
>     implementation project(':reactnativenotifications');
>     implementation 'com.google.firebase:firebase-core:16.0.7';
> }
> apply plugin: 'com.google.gms.google-services' // add this at the end of the file
> ```
> 
> MainApplication.java:
> 
> ```java
>  private final ReactNativeHost mReactNativeHost =
>    
>       @Override
>       protected List<ReactPackage> getPackages() {
>         @SuppressWarnings("UnnecessaryLocalVariable")
>         List<ReactPackage> packages = new PackageList(this).getPackages();
> 
>         //add the package here (note the this.getApplication())
>         packages.add(new RNNotificationsPackage(this.getApplication())); 
>         return packages;
>       }
> ```
> 
> **Ios**
> 
> ```
> cd ios
> pod install
> ```
> 
> And follow the steps here :https://github.com/wix/react-native-notifications/blob/2.1.5/docs/installation.md
> to edit the AppDelegate.m

Hi, of what you said here in the new version (RN0.61.5) was successful in getting build. But the application is crashing while opening. And I didn't make any changes to the application's first js files.

**Comment by Bilal-Abdeen** [comment]
I think have seen something like this. I am not sure about the best resolution though. I suggest trying to comment the following commands if you are using any of them. I suspect one of them is the culprit. 
NotificationsAndroid.setRegistrationTokenUpdateListener(onPushRegistered); NotificationsAndroid.setNotificationOpenedListener(onNotificationOpened);
NotificationsAndroid.setNotificationReceivedListener(onNotificationReceived);

Thanks and Regards, 
Bilal Abdeen --------------- 
    On Saturday, 14 December 2019, 04:53:37 am AEDT, Muhammet INAN <notifications@github.com> wrote:  
 
 

I was able to make it work with the version 2.1.5 and RN 0.61.2

Android
add to the react-native.config.js to ignore it on the auto-linking:
module.exports = {
  dependencies: {
    'react-native-notifications': {
      platforms: {
        android: null
      },
    },
 },
}
add to the settings.gradle:
include ':reactnativenotifications'
project(':reactnativenotifications').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-notifications/android/app')

build.gradle:
buildscript {
    ...
    dependencies {
        ...
        classpath 'com.google.gms:google-services:4.3.0' // <-- add this
    }
}

app/build.gradle:
android {
  defaultConfig {
     ...
     //add this
     missingDimensionStrategy "RNNotifications.reactNativeVersion", "reactNative60"
   }
}
dependencies {
    ...
    // add both
    implementation project(':reactnativenotifications');
    implementation 'com.google.firebase:firebase-core:16.0.7';
}
apply plugin: 'com.google.gms.google-services' // add this at the end of the file

MainApplication.java:
 private final ReactNativeHost mReactNativeHost =
   
      @Override
      protected List<ReactPackage> getPackages() {
        @SuppressWarnings("UnnecessaryLocalVariable")
        List<ReactPackage> packages = new PackageList(this).getPackages();

        //add the package here (note the this.getApplication())
        packages.add(new RNNotificationsPackage(this.getApplication())); 
        return packages;
      }
Ios
cd ios
pod install

And follow the steps here :https://github.com/wix/react-native-notifications/blob/2.1.5/docs/installation.md
to edit the AppDelegate.m


Hi, of what you said here in the new version (RN0.61.5) was successful in getting build. But the application is crashing while opening. And I didn't make any changes to the application's first js files.

**Comment by reactdevrocks** [comment]
where can i find react-native.config.js file? @Bilal-Abdeen @msantang78

**Comment by Bilal-Abdeen** [comment]
@reactdevrocks You can create this file at the root of your project (in the same folder where package.json file is.)

**Comment by reactdevrocks** [comment]
not working the above solution @Bilal-Abdeen 
module.exports = {
  dependencies: {
    'react-native-notifications': {
      platforms: {
        android: null
      },
    },
 },
}
and giving error
Cannot get property 'packageName' on null object

**Comment by Bilal-Abdeen** [comment]
I am sorry, mate. I have no idea what causes this error. --------------- 
    On Saturday, 14 December 2019, 11:25:51 pm AEDT, reactdevrocks <notifications@github.com> wrote:  
 
 
not working the above solution @Bilal-Abdeen
module.exports = {
dependencies: {
'react-native-notifications': {
platforms: {
android: null
},
},
},
}
and giving error
Cannot get property 'packageName' on null object

**Comment by matheusbaumgart** [comment]
Even after the changes above it still doesn't recognise the argument for me :( 

`constructor RNNotificationsPackage in class RNNotificationsPackage cannot be applied to given types;
      new RNNotificationsPackage(),
      ^
  required: Application
  found: no arguments
  reason: actual and formal argument lists differ in length`

**Comment by arnaudambro** [comment]
Really hate those bots that close an unresolved issue... what the point ??

**Comment by stefandima** [comment]
I'm unable to makeít work. I have
    "react": "16.9.0",
    "react-native": "0.61.5",
    "react-native-notifications": "^3.1.1" (downgraded from 3.1.2)
And i receive:
MainApplication.java:17: error: package com.wix.reactnativenotifications does not exist.
and obvious:
MainApplication.java:34: error: cannot 
find symbol
          packages.add(new RNNotificationsPackage(MainApplication.this));
                           ^
  symbol: class RNNotificationsPackage
I try even manual linking. I read everithing i could found.
Some help please.

**Comment by Bilal-Abdeen** [comment]
Please, double-check that you have followed the latest installation instructions, specifically the following step. 
https://github.com/wix/react-native-notifications/blob/master/docs/installation-android.md#step-4-add-firebase-core-package-and-apply-google-services-plugin-in-projectappbuildgradle

**Comment by stefandima** [comment]
That step is needed only if:
_Note: This section is only necessary in case you wish to be able to receive push notifications in your React-Native app._
But i want only to give notifications from application.
I dont know, and is not in my scope, to use Google FCM Service.

**Comment by ShaneMatthias** [comment]
> implementation project(':reactnativenotifications');

Hey, creating the config file in my root folder doesn't seem to be disabling auto-linking for android. Am I missing a setup process or something?

**Comment by ShaneMatthias** [comment]
> I was able to make it work with the version 2.1.5 and RN 0.61.2
> 
> **Android**
> add to the react-native.config.js to ignore it on the auto-linking:
> 
> ```js
> module.exports = {
>   dependencies: {
>     'react-native-notifications': {
>       platforms: {
>         android: null
>       },
>     },
>  },
> }
> ```
> 
> add to the settings.gradle:
> 
> ```
> include ':reactnativenotifications'
> project(':reactnativenotifications').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-notifications/android/app')
> ```
> 
> build.gradle:
> 
> ```
> buildscript {
>     ...
>     dependencies {
>         ...
>         classpath 'com.google.gms:google-services:4.3.0' // <-- add this
>     }
> }
> ```
> 
> app/build.gradle:
> 
> ```
> android {
>   defaultConfig {
>      ...
>      //add this
>      missingDimensionStrategy "RNNotifications.reactNativeVersion", "reactNative60"
>    }
> }
> dependencies {
>     ...
>     // add both
>     implementation project(':reactnativenotifications');
>     implementation 'com.google.firebase:firebase-core:16.0.7';
> }
> apply plugin: 'com.google.gms.google-services' // add this at the end of the file
> ```
> 
> MainApplication.java:
> 
> ```java
>  private final ReactNativeHost mReactNativeHost =
>    
>       @Override
>       protected List<ReactPackage> getPackages() {
>         @SuppressWarnings("UnnecessaryLocalVariable")
>         List<ReactPackage> packages = new PackageList(this).getPackages();
> 
>         //add the package here (note the this.getApplication())
>         packages.add(new RNNotificationsPackage(this.getApplication())); 
>         return packages;
>       }
> ```
> 
> **Ios**
> 
> ```
> cd ios
> pod install
> ```
> 
> And follow the steps here :https://github.com/wix/react-native-notifications/blob/2.1.5/docs/installation.md
> to edit the AppDelegate.m

Hey, creating the config file in my root folder doesn't seem to be disabling auto-linking for android. Am I missing a setup process or something?

**Comment by ShaneMatthias** [comment]
> Even after the changes above it still doesn't recognise the argument for me :(
> 
> `constructor RNNotificationsPackage in class RNNotificationsPackage cannot be applied to given types; new RNNotificationsPackage(), ^ required: Application found: no arguments reason: actual and formal argument lists differ in length`

Same, please help!
